apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "draftt-port-integration.fullname" . }}
  namespace: {{ .Values.appConfig.namespace }}
  labels:
    {{- include "draftt-port-integration.labels" . | nindent 4 }}
    {{ if .Values.deployment.labels }}
      {{- toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.deployment.annotations }}
      {{- toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "draftt-port-integration.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "draftt-port-integration.labels" . | nindent 8 }}
        {{- if .Values.deployment.labels }}
          {{- toYaml .Values.deployment.labels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.deployment.annotations }}
          {{- toYaml .Values.deployment.annotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.deployment.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.deployment.image.pullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: draftt-port-integration
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        env:
          - name: OCEAN__PORT__CLIENT_ID
            value: "{{ .Values.appConfig.port.clientId }}"
          - name: OCEAN__PORT__CLIENT_SECRET
            value: "{{ .Values.appConfig.port.clientSecret }}"
          - name: OCEAN__PORT__BASE_URL
            value: "{{ .Values.appConfig.port.baseUrl }}"
          - name: OCEAN__INTEGRATION__IDENTIFIER
            value: "{{ .Values.appConfig.integration.identifier }}"
          - name: OCEAN__EVENT_LISTENER__TYPE
            value: "{{ .Values.appConfig.port.eventListenerType }}"
          - name: OCEAN__INITIALIZE_PORT_RESOURCES
            value: "{{ .Values.appConfig.port.initializePortResources }}"
          {{- if .Values.appConfig.draftt.drafttApiToken }}
          - name: OCEAN__INTEGRATION__CONFIG__DRAFTT_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.appConfig.draftt.drafttApiToken.secretName }}"
                key: "{{ .Values.appConfig.draftt.drafttApiToken.secretKey }}"
          {{- end }}
      restartPolicy: {{ default "Always" .Values.deployment.restartPolicy }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector: {{ .Values.deployment.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }} 