apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}-readonly
  labels:
    {{- include "draftt-explorer.labels" . | nindent 4 }}
    {{ if .Values.clusterRole.labels }}
    {{- toYaml .Values.clusterRole.labels | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["*"] # A wildcard to include all API groups
  resources: ["*"] # A wildcard to include all resources
  verbs: ["get", "list", "watch"]  # read only access
