apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.appConfig.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name }}-readonly
  apiGroup: rbac.authorization.k8s.io
