apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-binding
  namespace: {{ .Values.appConfig.namespace }}
  labels:
    {{- include "draftt-explorer.labels" . | nindent 4 }}
    {{ if .Values.clusterRoleBinding.labels }}
    {{- toYaml .Values.clusterRoleBinding.labels | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.appConfig.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name }}-readonly
  apiGroup: rbac.authorization.k8s.io
