{{- $legacyCronJob := deepCopy .Values.legacyCronJob -}}
{{- with .Values.cronjob }}
{{- $legacyCronJob = mergeOverwrite $legacyCronJob (deepCopy .) -}}
{{- end }}
{{- with .Values.image }}
{{- $_ := set $legacyCronJob "image" (mergeOverwrite (deepCopy $legacyCronJob.image) (deepCopy .)) -}}
{{- end }}
{{- with .Values.resources }}
{{- $_ := set $legacyCronJob "resources" (mergeOverwrite (deepCopy $legacyCronJob.resources) (deepCopy .)) -}}
{{- end }}
{{- if $legacyCronJob.enabled -}}
{{- $legacyAPIEndpoint := printf "%s/component/k8s" (include "draftt-k8s-explorer.apiBaseUrl" .) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "draftt-k8s-explorer.fullname" . }}
  namespace: {{ .Values.appConfig.namespace | default .Release.Namespace }}
  labels:
    {{- include "draftt-explorer.labels" . | nindent 4 }}
    {{ if $legacyCronJob.labels }}
      {{- toYaml $legacyCronJob.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $legacyCronJob.annotations }}
      {{- toYaml $legacyCronJob.annotations | nindent 4 }}
    {{- end }}
spec:
  schedule: "{{ $legacyCronJob.schedule }}"
  failedJobsHistoryLimit: {{ $legacyCronJob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $legacyCronJob.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ $legacyCronJob.maxRetries }}
      ttlSecondsAfterFinished: {{ $legacyCronJob.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "draftt-explorer.labels" . | nindent 12 }}
            {{- if $legacyCronJob.labels }}
              {{- toYaml $legacyCronJob.labels | nindent 12 }}
            {{- end }}
          annotations:
            {{- if $legacyCronJob.annotations }}
              {{- toYaml $legacyCronJob.annotations | nindent 12 }}
            {{- end }}
        spec:
          {{- if $legacyCronJob.image.pullSecrets }}
          imagePullSecrets:
          {{- toYaml $legacyCronJob.image.pullSecrets | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "draftt-k8s-explorer.serviceAccountName" . }}
          containers:
          - name: draftt-k8s-explorer
            image: "{{ $legacyCronJob.image.repository }}:{{ $legacyCronJob.image.tag }}"
            imagePullPolicy: {{ $legacyCronJob.image.pullPolicy }}
            resources:
              {{- toYaml $legacyCronJob.resources | nindent 14 }}
            env:
              # Environment variables based on the appConfig
              - name: DRAFTT_COMPONENT_IDENTIFIER
                value: "{{ tpl .Values.appConfig.clusterIdentifier . }}"
              {{- if .Values.appConfig.api.enabled }}
              - name: MODE
                value: "api"
              - name: DRAFTT_API_ENDPOINT
                value: "{{ tpl $legacyAPIEndpoint . }}"
              {{- if .Values.appConfig.api.drafttApiToken }}
              - name: DRAFTT_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.appConfig.api.drafttApiToken.secretName }}"
                    key: "{{ .Values.appConfig.api.drafttApiToken.secretKey }}"
              {{- end }}
              {{- end }}
              {{- if and .Values.appConfig.localMode.enabled (not .Values.appConfig.api.enabled) }}
              - name: MODE
                value: "local"
              {{- if .Values.appConfig.localMode.outputType }}
              - name: LOCAL_OUTPUT_MODE
                value: "{{ .Values.appConfig.localMode.outputType }}"
              {{- end }}
              {{- end }}
              {{- if .Values.appConfig.logLevel }}
              - name: LOG_LEVEL
                value: "{{ .Values.appConfig.logLevel }}"
              {{- end }}
          restartPolicy: {{ default "OnFailure" $legacyCronJob.restartPolicy }}
          {{- if $legacyCronJob.nodeSelector }}
          nodeSelector: {{ $legacyCronJob.nodeSelector | toYaml | nindent 12 }}
          {{- end }}
          {{- if $legacyCronJob.tolerations }}
          tolerations:
            {{- toYaml $legacyCronJob.tolerations | nindent 12 }}
          {{- end }}
          {{- if $legacyCronJob.affinity }}
          affinity:
            {{- toYaml $legacyCronJob.affinity | nindent 12 }}
          {{- end }}
{{- end -}}
