{{- $cronJob := deepCopy .Values.cronJob -}}
{{- with .Values.cronjob }}
{{- $cronJob = mergeOverwrite $cronJob (deepCopy .) -}}
{{- end }}
{{- with .Values.image }}
{{- $_ := set $cronJob "image" (mergeOverwrite (deepCopy $cronJob.image) (deepCopy .)) -}}
{{- end }}
{{- with .Values.resources }}
{{- $_ := set $cronJob "resources" (mergeOverwrite (deepCopy $cronJob.resources) (deepCopy .)) -}}
{{- end }}
{{- if $cronJob.enabled -}}
{{- $apiEndpoint := printf "%s/component/k8s" (include "draftt-k8s-explorer.apiBaseUrl" .) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "draftt-k8s-explorer.fullname" . }}
  namespace: {{ .Values.appConfig.namespace | default .Release.Namespace }}
  labels:
    {{- include "draftt-explorer.labels" . | nindent 4 }}
    {{ if $cronJob.labels }}
      {{- toYaml $cronJob.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $cronJob.annotations }}
      {{- toYaml $cronJob.annotations | nindent 4 }}
    {{- end }}
spec:
  schedule: "{{ $cronJob.schedule }}"
  failedJobsHistoryLimit: {{ $cronJob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $cronJob.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ $cronJob.maxRetries }}
      ttlSecondsAfterFinished: {{ $cronJob.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "draftt-explorer.labels" . | nindent 12 }}
            {{- if $cronJob.labels }}
              {{- toYaml $cronJob.labels | nindent 12 }}
            {{- end }}
          annotations:
            {{- if $cronJob.annotations }}
              {{- toYaml $cronJob.annotations | nindent 12 }}
            {{- end }}
        spec:
          {{- if $cronJob.image.pullSecrets }}
          imagePullSecrets:
          {{- toYaml $cronJob.image.pullSecrets | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "draftt-k8s-explorer.serviceAccountName" . }}
          containers:
          - name: draftt-k8s-explorer
            image: "{{ $cronJob.image.repository }}:{{ $cronJob.image.tag }}"
            imagePullPolicy: {{ $cronJob.image.pullPolicy }}
            resources:
              {{- toYaml $cronJob.resources | nindent 14 }}
            env:
              # Environment variables based on the appConfig
              - name: DRAFTT_COMPONENT_IDENTIFIER
                value: "{{ tpl .Values.appConfig.clusterIdentifier . }}"
              {{- if .Values.appConfig.api.enabled }}
              - name: MODE
                value: "api"
              - name: DRAFTT_API_ENDPOINT
                value: "{{ tpl $apiEndpoint . }}"
              {{- if .Values.appConfig.api.drafttApiToken }}
              - name: DRAFTT_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.appConfig.api.drafttApiToken.secretName }}"
                    key: "{{ .Values.appConfig.api.drafttApiToken.secretKey }}"
              {{- end }}
              {{- end }}
              {{- if and .Values.appConfig.localMode.enabled (not .Values.appConfig.api.enabled) }}
              - name: MODE
                value: "local"
              {{- if .Values.appConfig.localMode.outputType }}
              - name: LOCAL_OUTPUT_MODE
                value: "{{ .Values.appConfig.localMode.outputType }}"
              {{- end }}
              {{- end }}
              {{- if .Values.appConfig.logLevel }}
              - name: LOG_LEVEL
                value: "{{ .Values.appConfig.logLevel }}"
              {{- end }}
          restartPolicy: {{ default "OnFailure" $cronJob.restartPolicy }}
          {{- if $cronJob.nodeSelector }}
          nodeSelector: {{ $cronJob.nodeSelector | toYaml | nindent 12 }}
          {{- end }}
          {{- if $cronJob.tolerations }}
          tolerations:
            {{- toYaml $cronJob.tolerations | nindent 12 }}
          {{- end }}
          {{- if $cronJob.affinity }}
          affinity:
            {{- toYaml $cronJob.affinity | nindent 12 }}
          {{- end }}
{{- end -}}
