deployment:
  restartPolicy: "Always"  
  image:
    repository: public.ecr.aws/draftt-io/draftt-port-integration
    tag: 0.0.1
    pullPolicy: Always
    pullSecrets: []
  resources: # per recommendations, we did not set resource limits by default, you can set it here
    requests:
      cpu: 100m
      memory: 256Mi
  labels: {}
  annotations: {}
  nodeSelector: {}

appConfig:
  namespace: monitoring # The namespace that resources will be deployed on
  port:
    baseUrl: "https://api.getport.io"
    eventListenerType: "POLLING"
    initializePortResources: "true"
    portClientId:
      secretName: "draftt-port-integration"
      secretKey: "portClientId"
    portClientSecret:
      secretName: "draftt-port-integration"
      secretKey: "portClientSecret"
  integration:
    identifier: "draftt-io"
  draftt:
    drafttApiToken:
      secretName: "draftt-port-integration"
      secretKey: "drafttApiToken"
    